// +build !ignore_autogenerated

/*
Copyright 2020 The arhat.dev Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Hash) DeepCopyInto(out *Hash) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Hash.
func (in *Hash) DeepCopy() *Hash {
	if in == nil {
		return nil
	}
	out := new(Hash)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Maintenance) DeepCopyInto(out *Maintenance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Maintenance.
func (in *Maintenance) DeepCopy() *Maintenance {
	if in == nil {
		return nil
	}
	out := new(Maintenance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Maintenance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceDependency) DeepCopyInto(out *MaintenanceDependency) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceDependency.
func (in *MaintenanceDependency) DeepCopy() *MaintenanceDependency {
	if in == nil {
		return nil
	}
	out := new(MaintenanceDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceJob) DeepCopyInto(out *MaintenanceJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceJob.
func (in *MaintenanceJob) DeepCopy() *MaintenanceJob {
	if in == nil {
		return nil
	}
	out := new(MaintenanceJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaintenanceJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceJobList) DeepCopyInto(out *MaintenanceJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MaintenanceJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceJobList.
func (in *MaintenanceJobList) DeepCopy() *MaintenanceJobList {
	if in == nil {
		return nil
	}
	out := new(MaintenanceJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaintenanceJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceJobSpec) DeepCopyInto(out *MaintenanceJobSpec) {
	*out = *in
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]MaintenanceStage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceJobSpec.
func (in *MaintenanceJobSpec) DeepCopy() *MaintenanceJobSpec {
	if in == nil {
		return nil
	}
	out := new(MaintenanceJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceJobStageStatus) DeepCopyInto(out *MaintenanceJobStageStatus) {
	*out = *in
	if in.ScheduledAt != nil {
		in, out := &in.ScheduledAt, &out.ScheduledAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceJobStageStatus.
func (in *MaintenanceJobStageStatus) DeepCopy() *MaintenanceJobStageStatus {
	if in == nil {
		return nil
	}
	out := new(MaintenanceJobStageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceJobStatus) DeepCopyInto(out *MaintenanceJobStatus) {
	*out = *in
	if in.SucceededAt != nil {
		in, out := &in.SucceededAt, &out.SucceededAt
		*out = (*in).DeepCopy()
	}
	if in.FailedAt != nil {
		in, out := &in.FailedAt, &out.FailedAt
		*out = (*in).DeepCopy()
	}
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]MaintenanceJobStageStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceJobStatus.
func (in *MaintenanceJobStatus) DeepCopy() *MaintenanceJobStatus {
	if in == nil {
		return nil
	}
	out := new(MaintenanceJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceList) DeepCopyInto(out *MaintenanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Maintenance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceList.
func (in *MaintenanceList) DeepCopy() *MaintenanceList {
	if in == nil {
		return nil
	}
	out := new(MaintenanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MaintenanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceNodeDrainSpec) DeepCopyInto(out *MaintenanceNodeDrainSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make([]MaintenanceNodeSelector, len(*in))
		copy(*out, *in)
	}
	out.GracePeriod = in.GracePeriod
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceNodeDrainSpec.
func (in *MaintenanceNodeDrainSpec) DeepCopy() *MaintenanceNodeDrainSpec {
	if in == nil {
		return nil
	}
	out := new(MaintenanceNodeDrainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceNodeSelector) DeepCopyInto(out *MaintenanceNodeSelector) {
	*out = *in
	out.ValueFrom = in.ValueFrom
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceNodeSelector.
func (in *MaintenanceNodeSelector) DeepCopy() *MaintenanceNodeSelector {
	if in == nil {
		return nil
	}
	out := new(MaintenanceNodeSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceNodeUncordonSpec) DeepCopyInto(out *MaintenanceNodeUncordonSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make([]MaintenanceNodeSelector, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceNodeUncordonSpec.
func (in *MaintenanceNodeUncordonSpec) DeepCopy() *MaintenanceNodeUncordonSpec {
	if in == nil {
		return nil
	}
	out := new(MaintenanceNodeUncordonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenancePhaseAdmitted) DeepCopyInto(out *MaintenancePhaseAdmitted) {
	*out = *in
	if in.At != nil {
		in, out := &in.At, &out.At
		*out = (*in).DeepCopy()
	}
	out.By = in.By
	if in.ScheduleSince != nil {
		in, out := &in.ScheduleSince, &out.ScheduleSince
		*out = (*in).DeepCopy()
	}
	if in.ScheduleUntil != nil {
		in, out := &in.ScheduleUntil, &out.ScheduleUntil
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenancePhaseAdmitted.
func (in *MaintenancePhaseAdmitted) DeepCopy() *MaintenancePhaseAdmitted {
	if in == nil {
		return nil
	}
	out := new(MaintenancePhaseAdmitted)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenancePhaseFinished) DeepCopyInto(out *MaintenancePhaseFinished) {
	*out = *in
	if in.At != nil {
		in, out := &in.At, &out.At
		*out = (*in).DeepCopy()
	}
	out.By = in.By
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenancePhaseFinished.
func (in *MaintenancePhaseFinished) DeepCopy() *MaintenancePhaseFinished {
	if in == nil {
		return nil
	}
	out := new(MaintenancePhaseFinished)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenancePhaseScheduled) DeepCopyInto(out *MaintenancePhaseScheduled) {
	*out = *in
	if in.At != nil {
		in, out := &in.At, &out.At
		*out = (*in).DeepCopy()
	}
	out.By = in.By
	out.SpecSnapshotHash = in.SpecSnapshotHash
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenancePhaseScheduled.
func (in *MaintenancePhaseScheduled) DeepCopy() *MaintenancePhaseScheduled {
	if in == nil {
		return nil
	}
	out := new(MaintenancePhaseScheduled)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceSchedule) DeepCopyInto(out *MaintenanceSchedule) {
	*out = *in
	if in.Since != nil {
		in, out := &in.Since, &out.Since
		*out = (*in).DeepCopy()
	}
	out.Delay = in.Delay
	if in.Until != nil {
		in, out := &in.Until, &out.Until
		*out = (*in).DeepCopy()
	}
	out.Duration = in.Duration
	if in.Depends != nil {
		in, out := &in.Depends, &out.Depends
		*out = make([]MaintenanceDependency, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceSchedule.
func (in *MaintenanceSchedule) DeepCopy() *MaintenanceSchedule {
	if in == nil {
		return nil
	}
	out := new(MaintenanceSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceSpec) DeepCopyInto(out *MaintenanceSpec) {
	*out = *in
	if in.TargetNamespaces != nil {
		in, out := &in.TargetNamespaces, &out.TargetNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]NodeSpecificEnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]NodeSpecificEnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Schedule.DeepCopyInto(&out.Schedule)
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]MaintenanceStage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceSpec.
func (in *MaintenanceSpec) DeepCopy() *MaintenanceSpec {
	if in == nil {
		return nil
	}
	out := new(MaintenanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceStage) DeepCopyInto(out *MaintenanceStage) {
	*out = *in
	out.Delay = in.Delay
	out.Timeout = in.Timeout
	if in.Drain != nil {
		in, out := &in.Drain, &out.Drain
		*out = new(MaintenanceNodeDrainSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Uncordon != nil {
		in, out := &in.Uncordon, &out.Uncordon
		*out = new(MaintenanceNodeUncordonSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(v1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceStage.
func (in *MaintenanceStage) DeepCopy() *MaintenanceStage {
	if in == nil {
		return nil
	}
	out := new(MaintenanceStage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceStatus) DeepCopyInto(out *MaintenanceStatus) {
	*out = *in
	in.Admitted.DeepCopyInto(&out.Admitted)
	in.Scheduled.DeepCopyInto(&out.Scheduled)
	in.Finished.DeepCopyInto(&out.Finished)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceStatus.
func (in *MaintenanceStatus) DeepCopy() *MaintenanceStatus {
	if in == nil {
		return nil
	}
	out := new(MaintenanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSpecificEnvFromSource) DeepCopyInto(out *NodeSpecificEnvFromSource) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(ObjectNameRef)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(ObjectNameRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSpecificEnvFromSource.
func (in *NodeSpecificEnvFromSource) DeepCopy() *NodeSpecificEnvFromSource {
	if in == nil {
		return nil
	}
	out := new(NodeSpecificEnvFromSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSpecificEnvValueFrom) DeepCopyInto(out *NodeSpecificEnvValueFrom) {
	*out = *in
	if in.ConfigMapKeyRef != nil {
		in, out := &in.ConfigMapKeyRef, &out.ConfigMapKeyRef
		*out = new(ObjectNameKeyRef)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(ObjectNameKeyRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSpecificEnvValueFrom.
func (in *NodeSpecificEnvValueFrom) DeepCopy() *NodeSpecificEnvValueFrom {
	if in == nil {
		return nil
	}
	out := new(NodeSpecificEnvValueFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSpecificEnvVar) DeepCopyInto(out *NodeSpecificEnvVar) {
	*out = *in
	in.ValueFrom.DeepCopyInto(&out.ValueFrom)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSpecificEnvVar.
func (in *NodeSpecificEnvVar) DeepCopy() *NodeSpecificEnvVar {
	if in == nil {
		return nil
	}
	out := new(NodeSpecificEnvVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectNameKeyRef) DeepCopyInto(out *ObjectNameKeyRef) {
	*out = *in
	in.ObjectNameRef.DeepCopyInto(&out.ObjectNameRef)
	if in.KeyFrom != nil {
		in, out := &in.KeyFrom, &out.KeyFrom
		*out = new(ValueFrom)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectNameKeyRef.
func (in *ObjectNameKeyRef) DeepCopy() *ObjectNameKeyRef {
	if in == nil {
		return nil
	}
	out := new(ObjectNameKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectNameRef) DeepCopyInto(out *ObjectNameRef) {
	*out = *in
	if in.NameFrom != nil {
		in, out := &in.NameFrom, &out.NameFrom
		*out = new(ValueFrom)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectNameRef.
func (in *ObjectNameRef) DeepCopy() *ObjectNameRef {
	if in == nil {
		return nil
	}
	out := new(ObjectNameRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReference) DeepCopyInto(out *ResourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReference.
func (in *ResourceReference) DeepCopy() *ResourceReference {
	if in == nil {
		return nil
	}
	out := new(ResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueFrom) DeepCopyInto(out *ValueFrom) {
	*out = *in
	out.NodeFieldRef = in.NodeFieldRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueFrom.
func (in *ValueFrom) DeepCopy() *ValueFrom {
	if in == nil {
		return nil
	}
	out := new(ValueFrom)
	in.DeepCopyInto(out)
	return out
}
